services:
  - type: web
    name: soft-ocr-excel
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python ocr_pdf_to_excel_app.py
    region: oregon
    plan: free
    runtimeEnvVars: {}
    buildFilter:
      paths:
        - requirements.txt
        - ocr_pdf_to_excel_app.py
        - render.yaml
    preBuildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
